# Generated by Django 4.0.4 on 2023-01-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='discription',
            new_name='summary',
        ),
    ]
