# Generated by Django 4.0.4 on 2023-01-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_rename_example_exercise_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='summary',
            new_name='input_a',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='types',
            new_name='input_b',
        ),
    ]
