# Generated by Django 4.0.4 on 2023-01-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_rename_input_1_entry_input_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
