# Generated by Django 4.0.4 on 2023-01-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_alter_entry_date_alter_entry_image_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='video',
        ),
        migrations.AddField(
            model_name='playlist',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='capstone.video'),
        ),
    ]
