# Generated by Django 4.0.4 on 2023-01-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_rename_video_id_video_video_remove_playlist_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='item',
            field=models.ManyToManyField(blank=True, default=None, to='capstone.video'),
        ),
    ]
