# Generated by Django 4.0.4 on 2023-01-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_alter_playlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
