# Generated by Django 4.0.4 on 2023-01-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='default.png', upload_to='post_images'),
        ),
    ]
