# Generated by Django 4.0.4 on 2023-01-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0015_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
